### ISSUE TITLE
Creating contact list

### ISSUE THREAD

**Issue by stoicAlchemist** [danchoi/vmail#154]
When I create a contact list, vmail searches for the Sent Mail folder, in my case it doesn't find it, I see the request on my browser as sent, I don't know if the folder was re-named or what is the issue.

**Comment by RensTillmann** [comment]
Running vmail **v2.9.11**

I have the same issue, but I have **gmail.com** in English (US).
I have a "Sent" inbox which is named "Sent Mail" in the title header, and a "Trash" which is named "Bin" in the title header. But I am still getting this error message:

`Unknown Mailbox: [Gmail]/["Sent Mail"] (Failure) (Net::IMAP::NoResponseError)`

I have tried to set it manually in the .vmailrc to no avail.

```
mailbox_aliases:
  sent: ['Sent Mail']                                                                                        
  trash: [Bin]
```

Any idea how I can solve this issue? Clearly the "Sent Mail" isn't there even though in my gmail.com it is.
Is there a good way to find out about the labels my gmail is using, so that I can know for sure where the problem is coming from. The error message I suppose is the response from gmail API right? In that case it would mean the "Send Mail" just really does not exist, but when I look in gmail.com > Settings > [Labels] it shows me a inbox named "Sent" (under column System Labels). I have tried to set this in `mailbox_aliases` but still not working:

`Unknown Mailbox: [Gmail]/["Sent"] (Failure) (Net::IMAP::NoResponseError)`

Thanks.

**Comment by RensTillmann** [comment]
I found the problem after digging into the code itself and debugging a little.

For some reason the `contacts_extractor.rb` file retrieves either the mailbox aliases from the `.vmailrc` file or it will use the one from `vmail/defaults.rb`. And this file causes the error because the IMAP doesn't like the value being parsed as `["Sent Mail"]` instead it should be send as plain string like so: `Sent Mail`.

According to this [(Wiki page)](https://github.com/danchoi/vmail/wiki/Non-English(US)-Gmail-accounts) the `.vmailrc` should contain the following format:
```
mailbox_aliases:
  all: ['Alle Nachrichten']
  drafts: [Entwürfe]
  sent: [Gesendet]
```

Now the thing here is that I don't use german language in gmail I am using **English (US)**.

So what should have worked for me would be:
```
mailbox_aliases:
  sent: ['Sent Mail']
```

However that was not the case, instead I have to fill it in like so:
```
mailbox_aliases:
  sent: Sent Mail
```
This solves the problem :+1: 

I couldn't find anybody else with the same issue except for this created Issue, so I am wondering if I am the only one having this problem? If not then I think both the Wiki page and the code should be changed?
