### ISSUE TITLE
PATH issue on Arch Linux

### ISSUE THREAD

**Issue by sajattack** [danchoi/vmail#211]
The readme says 

> On some systems you may run into a PATH issue, where the system can't find the vmail command after installation. Please report this if you encounter this problem, and mention what system you're using.

Here's my report, I'm using Arch Linux

**Comment by sajattack** [comment]
Fixed by manually adding ~/.gem/ruby/2.4.0/bin to my path manually

**Comment by alter2000** [comment]
1. You should put this as a path, since Ruby (major) version changes will break the $PATH: 
`$(ruby -e 'print Gem.user_dir')/bin:`
2. It seems the issue is Arch-specific and [mentioned in the Wiki](https://wiki.archlinux.org/index.php/Ruby#Setup), besides you figured it out, so I think it should be closed.
